language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: bXMpZPM0bbXUMAXHNpCCDv6bs7VuIaOdudD9KUsBrfHaao6vy3N6x2emEqj0nmpXsbvO6jEewmGz2uDB9PFQcTN7NywB1qS2SvHQcWF/kpCpO8R8GxkvAvU/uAGGNdVidcnyZVxnVsNj8sLNSXU1p+Nl6n21AZ8CxB5yJ8dcqv1O3pS1B5rh9xohwLTn5vMul9ji0522urV1wNrynW6uRDLmlfCq4GY5uwYVlWPxCgKvkjBdjtKgFRpEo5Nr8xSi8MAQ5FagHyFIYKZIFZbBuyq06SOy30fJJ4egJQGUwgTskvT8kYsiA2RFN3jvD11IIBbmDB0rGmewLxfzEEPfOugnacYHKGl2PG1E918b4UceiIDSceQF3lrx3kiZtSNpdK3c0P3/JWT99S3VwxNUp6fDEBpIGGaO0TMM5G875PHn0//SI6wFzRlLBVewii4LoASHhopxmkGHUR7cjur8PflyYz7sHcXh5Pwk+2NS5b+fjTEcvzM1DOv+0sO3G/B7OOP/lFCPZYImsQFzUFa6K+pK97cCM/iRUJZzWEYm7J2gB691oSGNVHBSKT1i1q+xrzmIRNZMoR0FPyk0C5McanCsra+4D6HtO9uvTXsvCo9OiXin81BcXECkdCeQfPxxWLdrkxaE3r9WwRnSaRj+QaVmLXOI63p6rvWsRNSKjiI=
