language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: Az9gaK22pRQHFVqKZwpGO5p22dAdfTfsCv0YoL9Qm57x9QiOf/bFfobKIgQRGH5NceSoTtiETufeZP/mCq4RWouUQzr6qFYGdaiRO/Y+l/AaIcMAyTKOCdKnGHg0PZCLK3V5KXMAklBL9fgVzcIc80pwOGy0mdxFl6ZnsZTHl0B4Lv00WX106YpwRnZIH0PucxO3rEFMn5pUo1QCnGCW1WD8ukWX/ACubp9hUklioNHEX1UhOXe3tNEQSXxYTn/SayvcHZnv+wL7scjCkku5r657wai78okTxb/6wEaQdpvpK0ClQsdDUVNB/C2j2bpj+vX1Sq5wsrSDcpJhpGqFNXn1vAH0EdvjJFwcZiLD7PWj0QzI881fzDvuKuE6ulY+ZTSFQ8zYbXxqHeDSS9rEJ9Lc17CuT51rTLHYZfbKf/2q9u7qT2331QxzKMv/i3DeZIm1nR456kbq085BYkxWRxH1OocxSAszEmGcsrj64wldRZw2hZtIy0baeLIjf5zPuA2cSSolNuZxyYRy6lPx1dqyuNwVeOXutLCvmmhreMxLMEzXQfju/g6yHVm4nu9LyawICJT/ZC6h7FX29TCFo2YBp6MG7DpOSGX5cf39AeiiILKNUplDsKg34IEc86cXeGIrjRF1kvfwV6rYW1660jfyXOWMrBzk7RpozQvkgsM=
  app: keeping-tabs-on-taps-api
  on:
    repo: ramingar/keeping-tabs-on-taps-API
